### PR TITLE
Fixed uWebSocket method signatures mismatch

### PR DESCRIPTION
**Pull request by bydavy**
I can't compile the project on Ubuntu (what about other platforms?). The method signature for uWebsocket doesn't match the header file. I provided a fix which compile successfully on Ubuntu, can someone confirm it still compiles on Windows and Mac?

### CODE REVIEW

**Comment by bydavy** [comment]
The compilation errors were against uWebSockets v0.14.3

**Comment by bydavy** [comment]
Here are the compilation errors for reference:

> cmake .. && make && ./mpc
-- Configuring done
-- Generating done
-- Build files have been written to: CarND-MPC-Project/build
[ 33%] Building CXX object CMakeFiles/mpc.dir/src/main.cpp.o
CarND-MPC-Project/src/main.cpp: In function ‘int main()’:
CarND-MPC-Project/src/main.cpp:151:4: error: no matching function for call to ‘uWS::Hub::onMessage(main()::<lambda(uWS::WebSocket<true>, char*, size_t, uWS::OpCode)>)’
   });
    ^
In file included from /usr/include/uWS/Hub.h:4:0,
                 from /usr/include/uWS/uWS.h:4,
                 from CarND-MPC-Project/src/main.cpp:2:
/usr/include/uWS/Group.h:69:10: note: candidate: void uWS::Group<isServer>::onMessage(std::function<void(uWS::WebSocket<isServer>*, char*, long unsigned int, uWS::OpCode)>) [with bool isServer = true]
     void onMessage(std::function<void(WebSocket<isServer> *, char *, size_t, OpCode)> handler);
          ^~~~~~~~~
/usr/include/uWS/Group.h:69:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, char*, size_t, uWS::OpCode)>’ to ‘std::function<void(uWS::WebSocket<true>*, char*, long unsigned int, uWS::OpCode)>’
/usr/include/uWS/Group.h:69:10: note: candidate: void uWS::Group<isServer>::onMessage(std::function<void(uWS::WebSocket<isServer>*, char*, long unsigned int, uWS::OpCode)>) [with bool isServer = false]
/usr/include/uWS/Group.h:69:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, char*, size_t, uWS::OpCode)>’ to ‘std::function<void(uWS::WebSocket<false>*, char*, long unsigned int, uWS::OpCode)>’
CarND-MPC-Project/src/main.cpp:169:4: error: no matching function for call to ‘uWS::Hub::onConnection(main()::<lambda(uWS::WebSocket<true>, uWS::HttpRequest)>)’
   });
    ^
In file included from /usr/include/uWS/Hub.h:4:0,
                 from /usr/include/uWS/uWS.h:4,
                 from CarND-MPC-Project/src/main.cpp:2:
/usr/include/uWS/Group.h:67:10: note: candidate: void uWS::Group<isServer>::onConnection(std::function<void(uWS::WebSocket<isServer>*, uWS::HttpRequest)>) [with bool isServer = true]
     void onConnection(std::function<void(WebSocket<isServer> *, HttpRequest)> handler);
          ^~~~~~~~~~~~
/usr/include/uWS/Group.h:67:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, uWS::HttpRequest)>’ to ‘std::function<void(uWS::WebSocket<true>*, uWS::HttpRequest)>’
/usr/include/uWS/Group.h:67:10: note: candidate: void uWS::Group<isServer>::onConnection(std::function<void(uWS::WebSocket<isServer>*, uWS::HttpRequest)>) [with bool isServer = false]
/usr/include/uWS/Group.h:67:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, uWS::HttpRequest)>’ to ‘std::function<void(uWS::WebSocket<false>*, uWS::HttpRequest)>’
CarND-MPC-Project/src/main.cpp:175:4: error: no matching function for call to ‘uWS::Hub::onDisconnection(main()::<lambda(uWS::WebSocket<true>, int, char*, size_t)>)’
   });
    ^
In file included from /usr/include/uWS/Hub.h:4:0,
                 from /usr/include/uWS/uWS.h:4,
                 from CarND-MPC-Project/src/main.cpp:2:
/usr/include/uWS/Group.h:70:10: note: candidate: void uWS::Group<isServer>::onDisconnection(std::function<void(uWS::WebSocket<isServer>*, int, char*, long unsigned int)>) [with bool isServer = true]
     void onDisconnection(std::function<void(WebSocket<isServer> *, int code, char *message, size_t length)> handler);
          ^~~~~~~~~~~~~~~
/usr/include/uWS/Group.h:70:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, int, char*, size_t)>’ to ‘std::function<void(uWS::WebSocket<true>*, int, char*, long unsigned int)>’
/usr/include/uWS/Group.h:70:10: note: candidate: void uWS::Group<isServer>::onDisconnection(std::function<void(uWS::WebSocket<isServer>*, int, char*, long unsigned int)>) [with bool isServer = false]
/usr/include/uWS/Group.h:70:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, int, char*, size_t)>’ to ‘std::function<void(uWS::WebSocket<false>*, int, char*, long unsigned int)>’
CMakeFiles/mpc.dir/build.make:86: recipe for target 'CMakeFiles/mpc.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mpc.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mpc.dir/all' failed
make[1]: *** [CMakeFiles/mpc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by domluna** [comment]
@bydavy I'm guessing the `install_ubuntu.sh` script didn't work for you? It looks like signatures were changed in a recent version.

**Comment by bydavy** [comment]
I tried uWebSockets v0.14.3 and install_ubuntu.sh (aka uWebSockets master) and I hit this error in both cases.

**Comment by domluna** [comment]
@bydavy an important part was commented out https://github.com/udacity/CarND-MPC-Project/blob/master/install-ubuntu.sh#L6. At that checkout the script should work.

**Comment by bydavy** [comment]
I confirm [this commit](https://github.com/udacity/CarND-MPC-Project/commit/57287d011027c003445c586eb1d26e75a7c7bd87) fixed my issue. uWebSockets has changed some method signatures "recently" and it was the reason of the failure. Pulling the given git hash will ensure to use the expected version of uWebSockets.

**Comment by bydavy** [comment]
Thank you for the fix @domluna !

**Comment by TIEHua** [comment]
fatal error: uWS/uWS.h: No such file or directory
I don't know why

**Comment by TIEHua** [comment]
fatal error: uWS/uWS.h: No such file or directory
I don't know why

**Comment by TIEHua** [comment]
fatal error: uWS/uWS.h: No such file or directory
I don't know why

**Pull request closed without merging**
